[workspace]
members = [
    "packages/alloc",
    "packages/br-read",
    "packages/br-write",
    "packages/lz4",
    "packages/miniz",
    "packages/zstd-read",
    "packages/zstd-write",
    "packages/zune",
]

[profile.release]
lto = true
codegen-units = 1
