[workspace]
members = [
    "packages/alloc",
    "packages/br-read",
    "packages/br-write",
    "packages/lz4",
    "packages/miniz",
    "packages/zstd",
]

[profile.release]
lto = true
codegen-units = 1
