[package]
name = "zstd"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zstd = { version = "0.12.2", default-features = false }
wasm-bindgen = "0.2.83"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
