[package]
name = "br-write"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
brotli = "6.0.0"
wasm-bindgen = "0.2.83"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
