[package]
name = "alloc-bump"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
bumpalo = { version = "3.19.0", features = ["collections"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
