[package]
name = "zune"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zune-inflate = "0.2.54"
wasm-bindgen.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
