[package]
name = "br-read"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
brotli-decompressor = "4.0.1"
wasm-bindgen = "0.2.95"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
