[tools]
"node" = { version = "22.18.0" }
"rust" = { version = "1.88.0", targets = "wasm32-unknown-unknown" }
"ubi:rustwasm/wasm-bindgen" = { version = "0.2.100", extract_all = "true" }
"ubi:WebAssembly/binaryen" = { version = "version_123", extract_all = "true", bin_path = "bin" }
"vfox:mise-plugins/vfox-clang" = { version = "14.0.6", os = "linux" }

[tasks."build:wasm"]
run = [
    "cargo build --target wasm32-unknown-unknown --release --workspace",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/alloc.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/alloc_bump.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/alloc_talc.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/br_read.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/br_write.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/libdeflate.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/lz4.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/miniz.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/zlib_rs.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/zstd_read.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/zstd_write.wasm",
    "wasm-bindgen --target web --out-dir ./src/wasm ./target/wasm32-unknown-unknown/release/zune.wasm",
    "wasm-opt -Os ./src/wasm/alloc_bg.wasm -o ./src/wasm/alloc_bg.wasm",
    "wasm-opt -Os ./src/wasm/alloc_bump_bg.wasm -o ./src/wasm/alloc_bump_bg.wasm",
    "wasm-opt -Os ./src/wasm/alloc_talc_bg.wasm -o ./src/wasm/alloc_talc_bg.wasm",
    "wasm-opt -Os ./src/wasm/br_read_bg.wasm -o ./src/wasm/br_read_bg.wasm",
    "wasm-opt -Os ./src/wasm/br_write_bg.wasm -o ./src/wasm/br_write_bg.wasm",
    "wasm-opt -Os ./src/wasm/libdeflate_bg.wasm -o ./src/wasm/libdeflate_bg.wasm",
    "wasm-opt -Os ./src/wasm/lz4_bg.wasm -o ./src/wasm/lz4_bg.wasm",
    "wasm-opt -Os ./src/wasm/miniz_bg.wasm -o ./src/wasm/miniz_bg.wasm",
    "wasm-opt -Os ./src/wasm/zlib_rs_bg.wasm -o ./src/wasm/zlib_rs_bg.wasm",
    "wasm-opt -Os ./src/wasm/zstd_read_bg.wasm -o ./src/wasm/zstd_read_bg.wasm",
    "wasm-opt -Os ./src/wasm/zstd_write_bg.wasm -o ./src/wasm/zstd_write_bg.wasm",
    "wasm-opt -Os ./src/wasm/zune_bg.wasm -o ./src/wasm/zune_bg.wasm",
]

[tasks."build"]
run = [
    "mise run build:wasm",
    "npm run build",
]

[tasks."dev"]
run = "npm run dev"
