[package]
name = "alloc-talc"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen.workspace = true
talc = { version = "4.4.3", default-features = false, features = ["lock_api"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
