[package]
name = "zstd-read"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
zstd = { version = "0.13.0", default-features = false, features = ["fat-lto"] }
wasm-bindgen.workspace = true
