name: CI

on:
  pull_request:
  push:
    branches: ['main']
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Npm Install
      run: npm ci
    - name: Build app
      run: npm run build:wasm && npm run build
    - run: npm run lint

  devcontainer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm install -g @devcontainers/cli
    - run: devcontainer build --workspace-folder .
